[font]
size = 14.0
allow_float_size = true

[[font.normal]]
family = "IosevkaFixed Nerd Font Mono"
style = "W400"

[[font.italic]]
family = "IosevkaFixed Nerd Font Mono"
style = "W400"

[[font.bold]]
family = "IosevkaFixed Nerd Font Mono"
style = "W400"

[[font.bold_italic]]
family = "IosevkaFixed Nerd Font Mono"
style = "W400"
