font_family      GeistMono Nerd Font Mono
bold_font        GeistMono Nerd Font Mono
italic_font      GeistMono Nerd Font Mono
bold_italic_font GeistMono Nerd Font Mono

font_size 11.6

# font_features GeistMonoNFM-Regular -liga

modify_font underline_position 0

modify_font cell_width 100%
modify_font cell_height 0px
modify_font baseline 0

window_padding_width 0 1
