font_family      family="Iosevka Nerd Font Mono" style=Regular
bold_font        family="Iosevka Nerd Font Mono" style=Regular
italic_font      family="Iosevka Nerd Font Mono" style=Regular
bold_italic_font family="Iosevka Nerd Font Mono" style=Regular

font_features IosevkaNFM -calt

font_size 13.0
