font_family      IosevkaFixed Nerd Font Mono
bold_font        IosevkaFixed Nerd Font Mono
italic_font      IosevkaFixed Nerd Font Mono
bold_italic_font IosevkaFixed Nerd Font Mono

font_size 13.0

modify_font underline_position 0

modify_font cell_width 94%
modify_font cell_height -1px
modify_font baseline 1

window_padding_width 0 3 0 3
