;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar

include-file = $HOME/.config/polybar/themes/custom_catppuccin_mocha/include-modules.ini

[bar/main]
width = 100%
height = 28
offset-y = 0
; bottom = true
fixed-center = true
; radius = 12

; border-top-size = 6
border-bottom-size = 0
; border-left-size = 6
; border-right-size = 6

; wm-restack = bspwm
wm-restack = i3

override-redirect = false

scroll-up = next
scroll-down = prev

enable-ipc = true

background = ${colors.bg}
foreground = ${colors.fg}

; separator = |

include-file = $HOME/.config/polybar/fonts.ini
include-file = $HOME/.config/polybar/modules.ini

tray-background = ${colors.bg}
tray-position = left
tray-maxsize = 18
tray-padding = 0
tray-offset-x = 0
tray-offset-y = 0

cursor-click = pointer
; cursor-scroll = ns-resize

[bar/tray]

monitor-strict = false
width = 20
height = 25
offset-x = 98% ######### offset values only dtermine the position of bar in the screen set it accordingly to your need
offset-y = 35
override-redirect = true ############### to make offset vales to work override-direct value must be true
fixed-center = true
background = ${colors.bg}
foreground = ${colors.fg}
radius = 8
line-size = 0
line-color = #f00
padding-left = 0
padding-right = 1
module-margin-left = 0
module-margin-right = 0
modules-right = sep
tray-position = right
tray-detached = false
tray-offset-x = 0
tray-offset-y = 0
tray-padding = 1
tray-maxsize = 20
tray-scale = 1.0
tray-background = ${colors.bg}

[settings]
screenchange-reload = true
