[module/date]
type = internal/date
interval = 1

; time = 󰃭 %a, %b %d - 󰥔 %I:%M
time = 󰥔 %I:%M %p
time-alt = 󰣆 %A, %B %d - 󰥔 %I:%M:%S %p

format = <label>
; format-prefix = %{T2}Date%{T-}
; format-prefix-foreground = ${colors.fg-alt}
format-padding = 1
label = %{T2}%time%%{T-}
; label-padding = 1
