[module/launcher]
type = custom/text
; content = 󰹪
content = 󰀻

; "content" has the same properties as "format-NAME"
content-foreground = ${colors.blue}
content-padding = 1

; "click-(left|middle|right)" will be executed using "/usr/bin/env sh -c $COMMAND"
click-left = ~/.config/polybar/scripts/rofi/drun.sh &
click-right = ~/.config/polybar/scripts/rofi/run.sh &
