[module/menu-apps]
type = custom/menu

; If true, <label-toggle> will be to the left of the menu items (default).
; If false, it will be on the right of all the items.
expand-right = true

; "menu-LEVEL-N" has the same properties as "label-NAME" with
; the additional "exec" property
;
; Commands will be executed using "/bin/sh -c $COMMAND"

format-padding = 1
label-open = 󰦪
label-close = 󰦪
label-separator = /
format-spacing = 1

menu-0-0 = 󱃹 Alacritty
menu-0-0-exec = alacritty &

; menu-0-0 = Internet
; menu-0-0-exec = menu-open-1
; menu-0-1 = Power
; menu-0-1-exec = menu-open-2

; menu-1-0 = Chrome
; menu-1-0-exec = google-chrome-stable &
; menu-1-1 = 󰌡 Spotify
; menu-1-1-exec = spotify &

; menu-2-0 = Reboot
; menu-2-0-exec = systemctl reboot
; menu-2-1 = Shutdown
; menu-2-1-exec = systemctl poweroff
