[module/sysmenu]
type = custom/text
; content = 󰐥
content = 󰤆

; content-background = ${color.primary}
content-foreground = ${colors.red}
content-padding = 1

click-left = ~/.config/polybar/scripts/powermenu/powermenu.sh &
