[module/system-bluetooth-bluetoothctl]
type = custom/script
format-prefix = %{T10}󰂯%{T-}
format-prefix-foreground = ${colors.blue}
format = <label>
format-padding = 1
exec = ~/.config/polybar/scripts/bluetoothctl/system-bluetooth-bluetoothctl.sh
tail = true
click-left = ~/.config/polybar/scripts/bluetoothctl/system-bluetooth-bluetoothctl.sh --toggle &
label = %{T2}%output%%{T-}
; label-padding = 1
label-padding-left = 1
label-foreground = ${colors.text}
