[module/wired]
type = internal/network
; interface = enp1s0f2
interface-type = wired
interval = 1.0


format-connected = <label-connected>
format-connected-padding = 1
; format-connected-prefix = %{T2}󱦜 %{T-}
format-connected-prefix = %{T2}󰈀 %{T-}
format-connected-prefix-foreground = ${colors.blue}
label-connected = %{T2}%local_ip%%{T-}
label-connected-foreground = ${colors.fg}

; format-disconnected = <label-disconnected>
; format-disconnected-padding = 1
; label-disconnected = %{T2}󱦜 %{T-}
; label-disconnected-foreground = ${colors.red}
