[font]
normal = { family = "CaskaydiaCove Nerd Font Mono", style = "Regular" }
bold = { family = "CaskaydiaCove Nerd Font Mono", style = "Regular" }
italic = { family = "CaskaydiaCove Nerd Font Mono", style = "Italic" }
bold_italic = { family = "CaskaydiaCove Nerd Font Mono", style = "Italic" }
size = 12.0
offset = { x = -1, y = 0 }
glyph_offset = { x = 0, y = 0 }

[window]
padding = { x = 0, y = 0 }
dynamic_padding = true
