[font]
normal = { family = "GeistMono Nerd Font Mono", style = "Regular" }
bold = { family = "GeistMono Nerd Font Mono", style = "Regular" }
italic = { family = "GeistMono Nerd Font Mono", style = "Italic" }
bold_italic = { family = "GeistMono Nerd Font Mono", style = "Italic" }

# normal size
size = 14.0
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }

[window]
padding = { x = 0, y = 0 }
dynamic_padding = true
