[font]
normal = { family = "Hack Nerd Font Mono", style = "Regular" }
bold = { family = "Hack Nerd Font Mono", style = "Regular" }
italic = { family = "Hack Nerd Font Mono", style = "Italic" }
bold_italic = { family = "Hack Nerd Font Mono", style = "Italic" }
size = 11.5
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }

[window]
padding = { x = 3, y = 1 }
dynamic_padding = false
