background            #000000
foreground            #FFFFFF
cursor                #FFFFFF
selection_background  #F81CE5

# black
color0                #000000

# bright black
color8                #808080

# red
color1                #FE0100

# bright red
color9                #FE0100

# green
color2                #33FF00

# bright green
color10               #33FF00

# yellow
color3                #FEFF00

# bright yellow
color11               #FEFF00

# blue
color4                #0066FF

# bright blue
color12               #0066FF

# magenta
color5                #CC00FF

# bright magenta
color13               #CC00FF

# cyan
color6                #00FFFF

# bright cyan
color14               #00FFFF

# white
color7                #D0D0D0

# bright white
color15               #FFFFFF

/* selection_foreground  #F81CE5 */
