background  #0f111a
foreground  #a6accd

cursor                #ffcb6b 

selection_foreground  #a6accd
selection_background  #1f2233

color0  #000000
color8  #ffffff

# red
color1                #f07178
# light red
color9                #f07178

# green
color2                #c3e88d
# light green
color10               #c3e88d

# yellow
color3                #ffcb6b
# light yellow
color11               #ffcb6b

# blue
color4                #82aaff
# light blue
color12               #82aaff

# magenta
color5                #c792ea
# light magenta
color13               #c792ea

# cyan
color6                #89ddff
# lighy cyan
color14               #89ddff

# light gray
color7                #a89984
# dark gray
color15               #928374

