background            #FAFAFA
foreground            #383A42
cursor                #000000
selection_background  #DCDCDC

# black
color0                #101012

# bright black
color8                #101012

# red
color1                #833B3B

# bright red
color9                #E45649

# green
color2                #50A14F

# bright green
color10               #50A14F

# yellow
color3                #7C5C20

# bright yellow
color11               #986801

# blue
color4                #4078F2

# bright blue
color12               #4078F2

# magenta
color5                #79428A

# bright magenta
color13               #A626A4

# cyan
color6                #2B5D63

# bright cyan
color14               #0184BC

# white
color7                #383A42

# bright white
color15               #383A42

/* selection_foreground  #F81CE5 */
