background  #1a212e 
foreground  #93a4c3 

cursor                #528bff 

selection_background  #2a324a

color0  #0c0e15 
color8  #93a4c3 

# red
color1                #f65866 
# light red
color9                #f65866 

# green
color2                #8bcd5b 
# light green
color10               #8bcd5b 

# yellow
color3                #efbd5d 
# light yellow
color11               #efbd5d 

# blue
color4                #41a7fc 
# light blue
color12               #41a7fc 

# magenta
color5                #c75ae8 
# light magenta
color13               #c75ae8 

# cyan
color6                #34bfd0 
# lighy cyan
color14               #34bfd0 

# light gray
color7                #a89984
# dark gray
color15               #928374

