# Theme
include ./colorschemes/catppuccin_mocha.conf

# -------------------------------------
# Options

# Fira Code
font_size 11.5

# Iosevka Fixed
# font_size 12.0

# Caskaydia Cove
# font_size 12.0

hide_window_decorations yes

window_padding_width 5 7

remember_window_size  no
initial_window_width  1100
initial_window_height 700

enable_audio_bell no

shell_integration disabled

cursor_shape underline
cursor_beam_thickness 1.0
cursor_underline_thickness 1.0

box_drawing_scale 0.001, 0.1, 1.5, 2

map ctrl+shift+t new_tab_with_cwd

# -------------------------------------

# Fonts

# Fira Code

font_family      Fira Code Regular Nerd Font Complete Mono
bold_font        Fira Code Regular Nerd Font Complete Mono

italic_font      Fira Code Regular Nerd Font Complete Mono
bold_italic_font Fira Code Regular Nerd Font Complete Mono

# -------------------------------------

# Iosevka Fixed

# font_family      Iosevka Fixed Nerd Font Complete Mono
# bold_font        Iosevka Fixed Nerd Font Complete Mono

# italic_font      Iosevka Fixed Italic Nerd Font Complete Mono
# bold_italic_font Iosevka Fixed Italic Nerd Font Complete Mono

# -------------------------------------

# Cascadia Code Light

# font_family      Caskaydia Cove Light Nerd Font Complete Mono
# bold_font        Caskaydia Cove Light Nerd Font Complete Mono

# italic_font      Caskaydia Cove Light Italic Nerd Font Complete Mono
# bold_italic_font Caskaydia Cove Light Italic Nerd Font Complete Mono

# -------------------------------------

# Cascadia Code SemiLight

# font_family      Caskaydia Cove SemiLight Nerd Font Complete Mono
# bold_font        Caskaydia Cove SemiLight Nerd Font Complete Mono

# italic_font      Caskaydia Cove SemiLight Italic Nerd Font Complete Mono
# bold_italic_font Caskaydia Cove SemiLight Italic Nerd Font Complete Mono

# -------------------------------------

# map kitty_mod+h previous_window
# map kitty_mod+l next_window
# map ctrl+f launch --type=overlay --stdin-source=@screen_scrollback /usr/bin/fzf --no-sort --no-mouse --exact -i
# map cmd+k send_text normal printf \'\\033[2J\\033[3J\\033[1;1H\'\x0d

# background_opacity         0.90
